name: Analyse SonarQube

on:
  push:
    branches:
      - main

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Installer Sonar Scanner
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip -O sonar.zip
          unzip sonar.zip -d /opt
          SCANNER_DIR=$(find /opt -type d -name "sonar-scanner-*")
          echo "$SCANNER_DIR/bin" >> $GITHUB_PATH
          echo "SonarQube Scanner installed in: $SCANNER_DIR"

      - name: Vérifier sonar-scanner
        run: |
          which sonar-scanner
          sonar-scanner -v

      - name: Lancer le script d’analyse
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: bash scripts/run_sonar.sh
